### PR TITLE
Fix markdown quotes

### LINKED ISSUE #52: markdown: bullet lists don't play nice with block quotes and code blocks
With the default config `require("headlines").setup()` and everything (nvim, nvim-treesitter, markdown parser, markdown_inline parser, ..) up-to-date, I get the following behaviors from markdown.

## block quote + list
code
<pre>
* list item
  > quote line 1
  > quote line 2. The bar is misplaced and ">" is not hidden.
</pre>
Result
image

## code block + list
code
<pre>
* item 1
  ```
  code block
  ```
* this item's bullet is hidden
</pre>
Result
image

### PR DESCRIPTION
**Pull request by lukas-reineke**
fix #52

### CODE REVIEW

**Comment by francium** [comment]
This is what I see 
image

**Comment by lukas-reineke** [comment]
can you paste the text here?

**Comment by francium** [comment]
# Hello

## World

- test
- Quote
  > this is a quote
  > this is second line of a quote
  > > this is a quite inside a quote
  > > > quote inside of a quote inside of a quote
  > level 1 quote
  > ```python
  > x = "this is code inside a quote"
  > ```
- Line
  ```python
  x = "some python code"
  ```
- Next line

I don't know how to paste markdown without it rendering

**Comment by lukas-reineke** [comment]
It looks correct for me


except for the codeblock inside quotes. And that's because the treesitter grammar doesn't understand that. Treesitter doesn't support that, so I can't support it either

**Pull request merged**
